### PR TITLE
Kitchen washer fridge

### PR DESCRIPTION
**Pull request by Tigul**
# Added 
* The inside shelves of the fridge door 
* The upper tray in the dish washer 

## Fridge 
* The Block on the left and right side of the shelves represent the round corners.

### CODE REVIEW

**Comment by gaya-** [comment]
1. rename fridge_door_shelve into fridge_door_shelf
2. clarify the necessity to comment out the simulated flag stuff

**Comment by ichumuh** [comment]
That doesn't seem right?
Screenshot from 2020-02-05 11-02-17

**Comment by gaya-** [comment]
@ichumuh could it be that we changed the pose of the handle because the mesh did not correspond to the real world? It doesn't look like Jonas did anything in his commits to break the pose of the handle.

**Comment by ichumuh** [comment]
@gaya- yes could be. I just measured to make sure. The real distance between handle and hinge is 9cm, which creates this hole. This means that the position was correct, but the handle mesh is too short and the door is too thin. @Tigul please revert the last commit and then I'll merge.

**Comment by gaya-** [comment]
@ichumuh I think @Tigul will not be working tomorrow, so if you want this PR earlier you can always revert stuff yourself after merging ;)

**Comment by Tigul** [comment]
@ichumuh  I reverted the change to the handle position.

**Comment by ichumuh** [comment]
thanks

**Pull request merged**
