### PR TITLE
moved w coordinate of quaternions to be the last component

### PR DESCRIPTION
**Pull request by daniel86**

### CODE REVIEW

**Comment by gaya-** [comment]
Hey Daniel, are you sure that it was not the last component before? I think it was. Most of the quaternions are "0 0 0 1" which corresponds to "x y z w". No you changed it to "y z w x". 

On the CRAM side we're using "current_object_pose" predicate to get the pose. Currently it returns "x y z q1 q2 q3 w", if you don't change that the CRAM code will be fine.

**Comment by bbferka** [comment]
I subscribe to Gaya's comment. These orientations that you changed looked correct (x y z w). All furniture pieces are by default oriented the same as the origin;

**Comment by daniel86** [comment]
_Currently it returns "x y z w q1 q2 q3"_

this is confusing. The signature is this:

    current_object_pose(Obj, [TX,TY,TZ,QW,QX,QY,QZ])

TX,TY,TZ is the translation vector from OWL as is, and
QW,QX,QY,QZ is the quaternion as is.

So you were using the QZ as the w component before? Then I guess
the transforms were already right and I only need to fix the KnowRob side
which in fact expects QW to be the first component at the moment.

**Comment by gaya-** [comment]
CRAM expects the order that I mentioned: "x y z w q1 q2 q3", KnowRob returns the pose in that exact order, so W comes first not last. If you change it to come last in "current_object_pose" please let me know, so I can update it in CRAM as well.

**Comment by daniel86** [comment]
`current_object_pose` returns exactly the same order as asserted in OWL. 
I would change the signature such that this is reflected (i.e., QW will be last then),
but the implementation still passes through the data from OWL without reordering or so.
If you use QW as w of quaternions at the moment, then this would indicate for me
that the assertions in OWL have wrong ordering with w the first component of asserted quaternions.

**Comment by gaya-** [comment]
This is the code that we use right now:

https://github.com/cram2/cram/blob/master/cram_knowrob/cram_semantic_map_utils/src/semantic-map.lisp#L207

As you can maybe see, we read the list from `current_object_pose` as a list of following order: `(x y z w q1 q2 q3)`, then when we create a pose out of it we reorder such that W goes last, as is common in ROS quaternions: `(cl-transforms:make-quaternion q1 q2 q3 w)`

**Comment by gaya-** [comment]
Which means that supposedly somewhere in KnowRob there is a reordering happening. Let me try to put a different order and see if messes things up.

**Comment by daniel86** [comment]
I was going through the KnowRob code, seemed to me that there was no reordering.

[here](https://github.com/knowrob/knowrob/blob/master/knowrob_objects/prolog/knowrob_objects.pl#L376) the quaternion and translations are read, using [this](https://github.com/knowrob/knowrob/blob/master/knowrob_common/prolog/knowrob_owl.pl#L598) helper.
And this should be basically it.

**Comment by gaya-** [comment]
@daniel86 @bbferka Ok, so I tested it. The `current_object_pose` does indeed not rearrange anything. Which means that the pull request makes sense. What does not make sense is the original orientations in the semantic map. There are quaternions like (0 1 0 0) in xyzw notation, which is a rotation of PI around Y, that's the kitchen sink counter top and some of the handles, which are upside-down. What is even more peculiar are the quaternions of "(0.70711 0.00000 0.70711 0)" which are a rotation of PI/2 around the axis `(0.7071 0.0 0.7071)`. I have no idea how this was working before, but it was, so I guess it does make sense...

**Comment by gaya-** [comment]
I tested the PR. This is the error that I'm getting:

INFO: Service registered: ServiceServer<ServiceDeclaration</json_prolog/finish, ServiceDescription<json_prolog_msgs/PrologFinish, bbfcda76036ebbe3d36caf7af80b260c>>>
java.lang.Exception: org.jpl7.PrologException: PrologException: error(java_exception('@'('J#00000140121429221848')), 'com.mongodb.MongoTimeoutException')
	at org.knowrob.json_prolog.JSONPrologNode$NextSolutionCallback.build(JSONPrologNode.java:312)
	at org.knowrob.json_prolog.JSONPrologNode$NextSolutionCallback.build(JSONPrologNode.java:276)
	at org.ros.internal.node.service.ServiceRequestHandler.handleRequest(ServiceRequestHandler.java:65)
	at org.ros.internal.node.service.ServiceRequestHandler.access$100(ServiceRequestHandler.java:38)
	at org.ros.internal.node.service.ServiceRequestHandler$1.run(ServiceRequestHandler.java:99)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.jpl7.PrologException: PrologException: error(java_exception('@'('J#00000140121429221848')), 'com.mongodb.MongoTimeoutException')
	at org.jpl7.Query.get1(Query.java:328)
	at org.jpl7.Query.hasNext(Query.java:185)
	at org.jpl7.Query.allSolutions(Query.java:538)
	at org.knowrob.json_prolog.query.AllSolutionsCommand.execute(AllSolutionsCommand.java:6)
	at org.knowrob.json_prolog.query.ThreadedQuery.run(ThreadedQuery.java:140)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more

I suspect that you added a default mongo lookup when asking for object poses. Please get rid of it. Not everybody uses mongo who wants to use the semantic ma.

**Comment by gaya-** [comment]
I cannot merge this PR until the problem with mongo is solved...

**Comment by daniel86** [comment]
I haven't changed anything within this pull request except of the OWL facts.

the mongo lookup is done since a long time by default if no other pose can be found and
urdfName property can be found, nothing I did recently should influence that.

However, in my working copy of KnowRob, with reworked knowrob_objects the behaviour might change.

**Comment by daniel86** [comment]
for testing just start a mongo server on localhost

**Pull request merged**
