### PR TITLE
Popcorn

### PR DESCRIPTION
**Pull request by hawkina**
popcorn table addition, xacro fixes for noetic. 
Tested by running popcorn demo from cram and running:
rosrun xacro xacro iai_kitchen_popcorn_python.urdf.xacro to assemble one urdf, and checked it with check_urdf. 
Also visualized it in Rviz.

### CODE REVIEW

**Comment by artnie** [comment]
Please do not add the `.urdf` files, only `.urdf.xacro`. For maintenance we can easily run into inconsistencies between the original xacro and the generated urdf. Rather generate it yourself with 
`xacro iai_kitchen_popcorn_python.urdf.xacro > iai_kitchen_popcorn_python.urdf`

**Comment by hawkina** [comment]
@artnie Hey. i've removed the urdf and added the popcorn owl file needed for knowrob. Is that okay?

**Comment by artnie** [comment]
> @artnie Hey. i've removed the urdf and added the popcorn owl file needed for knowrob. Is that okay?

Don't we need the popcorn environment urdf?  Is it somewhere else? And I don't know about the OWL file. If we can generate it easily, it would be better if we only have one root source of the environment, the XACRO, then generate ourselves the URDF and OWL from it. Because people working on the xacro won't necessarily adjust the urdf and owl, you know, then stuff get's out of sync.

**Comment by hawkina** [comment]
this is the urdf for popcorn: https://github.com/code-iai/iai_maps/blob/popcorn/iai_kitchen/urdf_obj/iai_kitchen_popcorn_python.urdf.xacro
it's the iai kitchen + popcorn table.

We can't generate the OWL automatically to my knowledge. This one was manually written by @AbhijitVyas for OpenEase.
That's why I removed the urdf. You can autogenerate it. You cannot autogenerate the OWL. (at least to my knowledge)

**Comment by artnie** [comment]
A bummer that we can't translate to OWL anymore. I know we had something like that before.

Please give me some info on how to run the popcorn demo in CRAM so I can test your PR.

**Comment by hawkina** [comment]
I only knew of the Autogeneration from UE via RobCoG :/ It probably needs to be adapted to SOMA...

yup. working on the instruction right now.

**Comment by artnie** [comment]
btw, can you put the refills-lab changes into a separate PR? I've never worked with refills and cant test if the changes are fine.

**Comment by hawkina** [comment]
ah got ahead of myself when committing. Sorry. it's just the "xacro:" prefix. I can remove it but it will be needed later anyway

**Comment by hawkina** [comment]
it's same changes as PR #85 :D

**Comment by artnie** [comment]
do you wanna accept #85 then? I mean, it's from tigul and you can review it right?

**Comment by hawkina** [comment]
checked, accepted and merged #85. removed dm_room changes from this PR since it works without them.

**Pull request merged**
