### PR TITLE
Adding toolholders

### PR DESCRIPTION
**Pull request by mgvargas**

### CODE REVIEW

**Comment by gheorghelisca** [comment]
@mgvargas i would like to merge your pull request but it has conflicts. could you please cancel this pull request add / fix the changes and make a new one. if you are not sure how to specifically do this, please come by me and we can discuss about that. thank you in advance! :)

**Comment by mgvargas** [comment]
@gheorghelisca the conflict is solved, please check it and let me know if it's correct. Thanks!

**Comment by gheorghelisca** [comment]
@mgvargas thanks for double checking. i pulled your last changes and tested again, but the tool holder is still too big [1]. what measurement unit is inventor using?

[1] tool_holder

**Comment by mgvargas** [comment]
I think the unit should be centimeters.

**Pull request merged**
