### PR TITLE
[iai_fridge]Adding a level in the fridge object

### PR DESCRIPTION
**Pull request by amar-fayaz**
Created a board inside the iai_fridge_main model to represent the different boards where the objects could be kept.
The existing model of the board is not a part of the iai_fridge_main but a part of fridge_area. (This has not been removed in this review)
The board is created using the URDF primitive _<box>_ tag. The values used are a cumulation of the real world measurement and in reference to the 3d model in iai_kitchen/meshes/misc/Fridge.obj

This is created as a separate object so that CRAM can address the levels inside a container as a separate entity and future containers with levels are expected to follow this pattern.

### CODE REVIEW

**Comment by gaya-** [comment]
apparently the measurement of the inside of the fridge is in the real world 47 cm, and the cad model has 50 inside. if we want to reach inside the fridge, this can cause problems

**Comment by amar-fayaz** [comment]
Adding the screenshots from Rviz with the added model

The red is the new model and the green under it is the old board
fridge front
fridge side
fridge top

**Comment by ichumuh** [comment]
The overlapping boards are not necessarily a problem for giskard but I think it can quickly lead to unintended behavior. If you want to change the collision avoidance distance you basically have max(distance set for new board, distance set for old board). I think it would be better the remove the old board from the fridge_area mesh.

**Comment by gaya-** [comment]
@ichumuh The PR is finished. Adjusting the origin center will not be done. Could you please take a look and merge this?

**Comment by gaya-** [comment]
Although I'm not sure if we want to mess with the DAE. Might revert that file back. It's used by OpenEASE ppl and there are lightning changes. Maybe only keep the new obj?

**Comment by ichumuh** [comment]
Fine with me, I only care about the obj. The current version looks good. You can merge it after its reverted.

**Comment by ichumuh** [comment]
On the other hand, I don't think its cool to for the dae and obj to be different. Don't you think the OpenEASE ppl would have to update the model anyway, because of the new floor?

**Comment by ichumuh** [comment]
There is one thing I've noticed. In the urdf the joint is at some random position and the visual has an offset. It would be better if the joint is where the visual is supposed to be and give the visual a 0 offset.

**Comment by gaya-** [comment]
Hmm, the new shelf layer is only added in the obj urdf as a simple object. So the dae would have to layer at all, because they don't use URDF, they only use CAD models... This is going to be problematic....

**Comment by gaya-** [comment]
The OpenEASE ppl would have to add a new entry into their semantic map for the shelf layer. I don't know if they will want to put effort into this.

**Comment by amar-fayaz** [comment]
> There is one thing I've noticed. In the urdf the joint is at some random position and the visual has an offset. It would be better if the joint is where the visual is supposed to be and give the visual a 0 offset.

I have fixed this in the previous commit I made. No change visually.

**Comment by gaya-** [comment]
@ichumuh can you check if everything's fine for you and merge? It's ok with me.

**Comment by ichumuh** [comment]
thanks.
@asilx can you please adjust our kitchen semantic map accordingly?

**Pull request merged**
