### PR TITLE
Fix meshes for openease

### PR DESCRIPTION
**Pull request by artnie**
Fixes https://github.com/code-iai/iai_maps/issues/43 
@daniel86, @gaya-  Could you check if the meshes behave properly in open ease?

### CODE REVIEW

**Comment by gaya-** [comment]
Thanks @artnie. Let's wait for @daniel86 or @asilx to say if it's fixed now. Have you tested in the bullet world and rviz?

**Comment by gaya-** [comment]
Hey @daniel86, could you please check if the meshes are fine in openease again?

**Comment by daniel86** [comment]
@gaya- looks fine now

**Comment by daniel86** [comment]
@artnie I have merged now the w-coordinate pull request that touches every pose. Since you also touched the OWL files we have a merge conflict. Could you please resolve this?

**Comment by daniel86** [comment]
@artnie ping

**Comment by artnie** [comment]
Theres still something wrong. Let me check this.

**Comment by artnie** [comment]
Nevermind. Should be fine now.

**Comment by gaya-** [comment]
@daniel86 @asilx Hello?

**Comment by daniel86** [comment]
@gaya- I will test it this week

**Comment by daniel86** [comment]
@arnie colors are ok, but transforms not. Frisge door offset and sink are wrong (your latest commit)

**Comment by gaya-** [comment]
@artnie please get the owl offsets correct. I think they were correct before so you probably just shouldn't have touched them.

**Comment by daniel86** [comment]
@artnie @gaya oh the wrong offsets were actually caused by an error in the OWL files. I have a fix for it in my iai_maps fork. I will merge this fix later today.

**Comment by Gaya** [comment]
Yo @daniel86. You keep tagging me, but I have nothing to do with this

**Pull request merged**
