### PR TITLE
Removed old ground maps and added a new one

### PR DESCRIPTION
**Pull request by gaya-**
Removed `map.pgm`, `map2` and `map3` and their corresponding launch files.

Added `map-2016-06-17`. Unfortunately, because I had to rotate the map the edges lost their sharpness. But as for the laser the edges are not particularly sharp anyway, it should be all good.

`maps.launch` file should simply point to the last up-to-date map (right now it points to `map-2016-06-17`).

### CODE REVIEW

**Comment by gaya-** [comment]
I would've merged it without a PR but I thought that GitHub email notifications are a good way to let people know about the changes.

Once merged, please close https://github.com/code-iai/iai_maps/issues/5.

**Comment by fairlight1337** [comment]
Why did I get assigned here?

**Comment by gaya-** [comment]
@fairlight1337 Because you used the old maps (at some point)? Adding new maps doesn't break stuff but removing the old ones might.

**Comment by fairlight1337** [comment]
Alright, thanks. I'm afraid that so many things changed by now that a new map isn't making life impossible. Also, I got the right version checked out, I'll keep it.

**Pull request merged**
